In [2]:
import numpy as np

In [6]:
v1 = np.array((1, 2, 3))
v2 = np.array((3, 3, 3))

print(v1.dot(v2))
print(v1 @ v2)

18
18


In [4]:
v1 = np.array((1, 2, 3))
v2 = np.array((3))

print(v1.dot(v2))
print(v1.dot(v2).sum())

[3 6 9]
18


In [22]:
print(v1.shape)
print(v1.cumprod())
print(v1.cumsum())

(3,)
[1 2 6]
[1 3 6]


In [6]:
np.random.rand(3,5)

array([[0.22395284, 0.43055767, 0.64949149, 0.46711186, 0.85923545],
       [0.0436204 , 0.1124224 , 0.48449691, 0.59281753, 0.57892249],
       [0.60462302, 0.90194966, 0.77531095, 0.35527804, 0.17328797]])